apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  OMRS_DB_HOSTNAME: {{ .Values.secrets.OMRS_DB_HOSTNAME | b64enc | quote }}
  OMRS_DB_USERNAME: {{ .Values.secrets.OMRS_DB_USERNAME | b64enc | quote }}
  OMRS_DB_PASSWORD: {{ .Values.secrets.OMRS_DB_PASSWORD | b64enc | quote }}
  OPENELIS_ATOMFEED_USER: {{ .Values.secrets.OPENELIS_ATOMFEED_USER | b64enc | quote }}
  OPENELIS_ATOMFEED_PASSWORD: {{ .Values.secrets.OPENELIS_ATOMFEED_PASSWORD | b64enc | quote }}
  MAIL_USER: {{ .Values.secrets.MAIL_USER | b64enc | quote }}
  MAIL_PASSWORD: {{ .Values.secrets.MAIL_PASSWORD | b64enc | quote }}
