name: Build and Publish OpenMRS Demo DB
on:
  push:
    branches: [master, BAH-1412]
    paths:
      - ".github/workflows/build_publish_openmrs_demoDB.yml"
      - "package/docker/demoDB/**"
      - "package/docker/docker_publish.sh"

  repository_dispatch:
    types: ["bahmni-scripts-trigger"]

env:
  BAHMNI_VERSION: 0.94
jobs:
  docker-build-publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          file: package/docker/demoDB/Dockerfile
          push: true
          tags: bahmni/openmrs-db:demo-${{env.BAHMNI_VERSION}}-${{github.run_number}},bahmni/openmrs-db:demo-latest
