name: Build and Publish OpenMRS
on:
  push:
    branches:
      - BAH-2620
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build-upload:
    name: Build & Upload OMRS Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: |
          ./mvnw --no-transfer-progress -U clean install
        env:
          USER_NAME: ${{ secrets.USERNAME }}
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: OMRS-Artifacts
          path: distro/target/