name: Build and Publish OpenMRS Fresh DB
on:
  push:
    branches: [master, BAH-1412]
    paths:
      - ".github/workflows/build_publish_openmrs_freshDB.yml"
      - "package/resources/openmrs_clean_dump.sql"
      - "package/docker/freshDB/**"
      - "package/docker/docker_publish.sh"


env:
  BAHMNI_VERSION: 0.94

jobs:
  docker-build-publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: ./package/docker/freshDB/docker_build.sh
      - name: Push Docker Image
        run: ./package/docker/docker_publish.sh bahmni/openmrs-db
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN}}
