name: Build and Publish OpenMRS Demo DB
on:
  push:
    branches: [master, BAH-1412]
    paths:
      - '.github/workflows/build_publish_openmrs_demoDB.yml'
      - 'package/docker/demodb.Dockerfile'
      - 'package/docker/scripts/docker_build_openmrs_demoDB.sh'
      - 'package/docker/scripts/docker_publish_openmrs_demoDB.sh'
  repository_dispatch:
    types: ["bahmni-scripts-trigger"]

env:
  BAHMNI_VERSION: 0.94
jobs:
  docker-build-publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout bahmni-scripts
        uses: actions/checkout@v2
        with:
          repository: Bahmni/bahmni-scripts
          path: bahmni-scripts
      - name: Build Docker Image
        run: ./package/docker/scripts/docker_build_openmrs_demoDB.sh
      - name: List Docker Images
        run: docker images
      - name: Push Docker Images
        run: ./package/docker/scripts/docker_publish_openmrs_demoDB.sh
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN}}
