name: Build and Publish OpenMRS Fresh DB
on:
  push:
    branches: [master, BAH-1412]
    paths:
      - ".github/workflows/build_publish_openmrs_freshDB.yml"
      - "package/resources/openmrs_clean_dump.sql"
      - "package/docker/freshDB/**"
      - "package/docker/docker_publish.sh"


env:
  BAHMNI_VERSION: 0.94

jobs:
  docker-build-publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          file: package/docker/freshDB/Dockerfile
          push: true
          tags: bahmni/openmrs-db:fresh-${{env.BAHMNI_VERSION}}-${{github.run_number}},bahmni/openmrs-db:fresh-latest