name: Continuous Integration
on:
  push:
    branches: 
    - master 
    - BAH-*
  repository_dispatch:
    types: ["openmrs-module-episodes-trigger","bahmni-core-trigger","openmrs-module-rulesengine-trigger","openmrs-module-bahmni.ie.apps-trigger"]
  workflow_dispatch:
env:
  BAHMNI_VERSION: 0.94
  BRANCH_NAME: master
jobs:
  build-package:
    name: Test and Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
       ./mvnw -s $GITHUB_WORKSPACE/.github/workflows/settings.xml clean install
      env:
        USER_NAME: ${{ secrets.USERNAME }}
        ACCESS_TOKEN: ${{ secrets.PASSWORD }}
  # docker-build-publish: